#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

. "$(dirname -- "$0")/../.env"

if [ "$(command -v docker)" -a $DOCKER_CONTAINER_NAME ]; then
  docker exec -u $(id -u):$(id -g) $DOCKER_CONTAINER_NAME npx lint-staged
else
  npx lint-staged
fi
